### ISSUE TITLE
Can you help me with your code?

### ISSUE THREAD

**Issue by alphashow** [gavazquez/NLineTester#1]
Hello

Can you help me with NLineTester python and C#?
when i test nline with wrong username and password and right key i get this response

> Failed to receive answer,check 14 byte config key for nline:

why i get that reply, the right response is to get

> wrong username and password

can you fix it, please?

Can you send me your email, please: "ibr1993m@gmail.com"

Thank you

**Comment by gavazquez** [comment]
That happens because AFTER sending the hello byte you received a response but when you send the LOGIN the server DOES NOT respond (he does not say if user is bad or not)

That error usually is because the 14 byte config has a mistake that's why it makes you check the error

**Comment by alphashow** [comment]
Thank you for your reply
You are right

But i test my Nline with right user, pass and key ==> result is "working"
Than i test  the same Nline with wrong user, right pass and right key ==> "Failed to receive answer,check 14 byte config key for nline"

i think must i get in state two "wrong username and password"
i use this project [php-newcamd](https://github.com/mszula/php-newcamd) and get the right result
I hope that clear
